Lesson 2
CodectiveOrg/bootcamp-2024-free-nextjs-amirsabrii pull request #3
Opened 2024-12-25 17:16 UTC by amirsabrii

بابت تاخیر و دیر وقت ارسال کردن عذرخواهی میکنم

2024-12-25 20:24 UTC, BijanProgrammer commented
> بابت تاخیر و دیر وقت ارسال کردن عذرخواهی میکنم

مشکلی نداره

2024-12-25 20:27 UTC, BijanProgrammer requested changes
فایل Workflow اضافه نشده

2024-12-25 20:27 UTC, BijanProgrammer commented on src/app/page.module.css
> +    } */
کامنت اضافه پاک شه

2024-12-25 20:27 UTC, BijanProgrammer commented on src/components/header/header.tsx
> +}
کامنت اضافه پاک شه

2024-12-26 15:45 UTC, amirsabrii commented
فایل Workflow رو اگر آمکانش هست اضافه نکنم و خودم دستی همخ کاراش رو میکنم و نیازی به چگ شدن از طرف گیت هاب ندارم

2024-12-27 14:50 UTC, BijanProgrammer commented
> فایل Workflow رو اگر آمکانش هست اضافه نکنم و خودم دستی همخ کاراش رو میکنم و نیازی به چگ شدن از طرف گیت هاب ندارم

باید طبق آموزش پیش برید و کاری که ازتون خواسته شده رو انجام بدید
چک‌کردن فرمت فایل‌ها برای اینه که من به عنوان Reviewer مطمئن باشم کدی که میره رو برنچ main به درستی فرمت شده

2024-12-29 06:03 UTC, BijanProgrammer approved these changes

2024-12-29 14:55 UTC, merged